# Generated by Django 3.2.15 on 2022-08-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
    ]
